### ISSUE TITLE
Homekit shows tv on when is off

### ISSUE THREAD

**Issue by ramirocaballero** [grzegorz914/homebridge-lgwebos-tv#42] opened 2020-05-26 14:35 UTC
Hi! When i turn off the tv by de Remote controller it doesn't change the state.

**Comment by grzegorz914** [comment] 2020-05-26 14:52
Log in debug mode?
TV model?

**Comment by ramirocaballero** [comment] 2020-05-26 14:58
[2020-5-26 11:54:10] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, set new Power state successful: ON
[2020-5-26 11:54:10] [Home Theater Sony] Publishing MQTT: cmnd/HomeTheater/IRsend = {Protocol:SONY,Bits: 15,Data: 0x540C}
[2020-5-26 11:54:10] [Home Theater Sony] Received MQTT: stat/HomeTheater/RESULT = {"IRSend":"Done"}
[2020-5-26 11:54:13] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, state: Online.
[2020-5-26 11:54:13] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, connecting...
[2020-5-26 11:54:13] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Power state successful: ON
[2020-5-26 11:54:13] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, connecting to RC socket...
[2020-5-26 11:54:13] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, RC socket connected.
[2020-5-26 11:54:13] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, requesting Device information.
[2020-5-26 11:54:14] [LgWebOsTv] -------- Televisor Living --------
[2020-5-26 11:54:14] [LgWebOsTv] Manufacturer: LG Electronics
[2020-5-26 11:54:14] [LgWebOsTv] Model: 55UK6550PSB
[2020-5-26 11:54:14] [LgWebOsTv] System: webOSTV 4.0
[2020-5-26 11:54:14] [LgWebOsTv] Serialnumber: 
[2020-5-26 11:54:14] [LgWebOsTv] Firmware: 10.45
[2020-5-26 11:54:14] [LgWebOsTv] ----------------------------------
[2020-5-26 11:54:16] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, state: Online.
[2020-5-26 11:54:19] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, requesting Device state.
[2020-5-26 11:54:19] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current App state data: {
  appId: 'com.webos.app.hdmi2',
  returnValue: true,
  windowId: '',
  processId: ''
}
[2020-5-26 11:54:19] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Power state data: { returnValue: true, state: 'Active' }
[2020-5-26 11:54:19] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Audio state data: {
  returnValue: true,
  scenario: 'mastervolume_ext_speaker_optical',
  volume: -1,
  muted: false
}
[2020-5-26 11:54:19] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Mute state: OFF
[2020-5-26 11:54:19] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Volume level: -1
[2020-5-26 11:54:19] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Channel data: { returnValue: false, errorCode: -1000, errorText: 'internal error' }
[2020-5-26 11:54:22] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, requesting Device state.
[2020-5-26 11:54:22] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Power state data: { returnValue: true, state: 'Active' }
[2020-5-26 11:54:22] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current App state data: {
  appId: 'com.webos.app.hdmi2',
  returnValue: true,
  windowId: '',
  processId: ''
}
[2020-5-26 11:54:22] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Audio state data: {
  returnValue: true,
  scenario: 'mastervolume_ext_speaker_optical',
  volume: -1,
  muted: false
}
[2020-5-26 11:54:22] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Mute state: OFF
[2020-5-26 11:54:22] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Volume level: -1
[2020-5-26 11:54:22] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Channel data: { returnValue: false, errorCode: -1000, errorText: 'internal error' }
[2020-5-26 11:54:25] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, requesting Device state.
[2020-5-26 11:54:25] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Power state data: { returnValue: true, state: 'Active' }
[2020-5-26 11:54:25] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current App state data: {
  appId: 'com.webos.app.hdmi2',
  returnValue: true,
  windowId: '',
  processId: ''
}
[2020-5-26 11:54:25] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Audio state data: {
  returnValue: true,
  scenario: 'mastervolume_ext_speaker_optical',
  volume: -1,
  muted: false
}
[2020-5-26 11:54:25] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Mute state: OFF
[2020-5-26 11:54:25] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Volume level: -1
[2020-5-26 11:54:25] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Channel data: { returnValue: false, errorCode: -1000, errorText: 'internal error' }
[2020-5-26 11:54:28] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, requesting Device state.
[2020-5-26 11:54:28] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current App state data: {
  appId: 'com.webos.app.hdmi2',
  returnValue: true,
  windowId: '',
  processId: ''
}
[2020-5-26 11:54:28] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Power state data: { returnValue: true, state: 'Active' }
[2020-5-26 11:54:28] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Audio state data: {
  returnValue: true,
  scenario: 'mastervolume_ext_speaker_optical',
  volume: -1,
  muted: false
}
[2020-5-26 11:54:28] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Mute state: OFF
[2020-5-26 11:54:28] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Volume level: -1
[2020-5-26 11:54:28] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Channel data: { returnValue: false, errorCode: -1000, errorText: 'internal error' }
[2020-5-26 11:54:31] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, requesting Device state.
[2020-5-26 11:54:31] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Power state data: { returnValue: true, state: 'Active' }
[2020-5-26 11:54:31] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current App state data: {
  appId: 'com.webos.app.hdmi2',
  returnValue: true,
  windowId: '',
  processId: ''
}
[2020-5-26 11:54:31] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Audio state data: {
  returnValue: true,
  scenario: 'mastervolume_ext_speaker_optical',
  volume: -1,
  muted: false
}
[2020-5-26 11:54:31] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Mute state: OFF
[2020-5-26 11:54:31] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Volume level: -1
[2020-5-26 11:54:31] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Channel data: { returnValue: false, errorCode: -1000, errorText: 'internal error' }
[2020-5-26 11:54:32] [Sensor MQTT 01] Received MQTT: cmnd/puerta_heladera/POWER3 = ON
[2020-5-26 11:54:32] [Sensor MQTT 01] **Fakegato-timer: addData  Sensor MQTT 01 { time: 1590504872, status: 1 }  immediate:  true
[2020-5-26 11:54:32] [Sensor MQTT 01] **Fakegato-timer: executeImmediateCallback**
[2020-5-26 11:54:32] [Sensor MQTT 01] **Fakegato-timer callbackMotion:  Sensor MQTT 01 , immediate:  true , entry:  { time: 1590504872, status: 1 }
[2020-5-26 11:54:34] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, requesting Device state.
[2020-5-26 11:54:34] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Power state data: { returnValue: true, state: 'Active' }
[2020-5-26 11:54:34] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current App state data: {
  appId: 'com.webos.app.hdmi2',
  returnValue: true,
  windowId: '',
  processId: ''
}
[2020-5-26 11:54:34] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Audio state data: {
  returnValue: true,
  scenario: 'mastervolume_ext_speaker_optical',
  volume: -1,
  muted: false
}
[2020-5-26 11:54:34] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Mute state: OFF
[2020-5-26 11:54:34] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Volume level: -1
[2020-5-26 11:54:34] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, get current Channel data: { returnValue: false, errorCode: -1000, errorText: 'internal error' }
[2020-5-26 11:54:42] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, state: Offline.


Here i turn it off by the controller but still ON in home app 
Model: 55UK6550PSB

**Comment by grzegorz914** [comment] 2020-05-26 15:03
i don't see that U turn the TV OFF, its not in the log

**Comment by ramirocaballero** [comment] 2020-05-26 15:05
[2020-5-26 11:54:42] [LgWebOsTv] Device: 10.0.1.22 Televisor Living, state: Offline.
what does it means? Nothing appears when i turn off. Thats the problem, maybe some configuration on the tv?

**Comment by grzegorz914** [comment] 2020-05-26 15:07
ah OK, nothin in log after this

**Comment by ramirocaballero** [comment] 2020-05-26 15:08
no, thats all

**Comment by ramirocaballero** [comment] 2020-05-26 15:09
Here is something new... 

TypeError: callback is not a function
    at lgwebosTvDevice.getPower (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:599:3)
    at LGTV.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:198:9)
    at LGTV.emit (events.js:310:20)
    at WebSocketConnection.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:108:18)
    at WebSocketConnection.emit (events.js:310:20)
    at WebSocketConnection.handleSocketClose (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at Socket.emit (events.js:310:20)
    at TCP.<anonymous> (net.js:672:12)

**Comment by grzegorz914** [comment] 2020-05-26 15:11
Offline is that TV is not available on the network anymore. 
Please make update and check again

**Comment by ramirocaballero** [comment] 2020-05-26 15:17
It works, but only when i close and re open home app

**Comment by grzegorz914** [comment] 2020-05-26 15:32
update again

**Comment by ramirocaballero** [comment] 2020-05-26 15:37
Still same. Only updates when re open Home app

**Comment by grzegorz914** [comment] 2020-05-26 16:02
check again

**Comment by ramirocaballero** [comment] 2020-05-26 16:09
Now works when i turn it On, but sill need to re open the app to turn int off. Other thing has happen. When i turn on the tv in the app, it turns on and off by it self and after a few miliseconds appears on again. That is a problem for me because i have an automation with an IR Remote that turns on my home theater but when that happens it turns it off. Sorry for my english

**Comment by angyp** [comment] 2020-05-26 22:31
The problem is that it takes approx 1 min 18 seconds to transition from offline (when you turn it off with the LG TV remote) to disconnected (when it shows as off in the home app) 

[5/27/2020, 8:25:18 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, state: Offline.
[5/27/2020, 8:26:37 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, disconnected.

**Comment by angyp** [comment] 2020-05-26 22:34
If it used the offline state instead of the disconnected sate it would work perfectly.

**Comment by justinrhodes** [comment] 2020-05-27 00:11
I am having this same issue. Can only control the TV with the Home App after the TV is already on. Once the TV is “off” I can no longer control it. At least after it’s been sitting off for a while like mentioned above.

**Comment by grzegorz914** [comment] 2020-05-27 04:53
> The problem is that it takes approx 1 min 18 seconds to transition from offline (when you turn it off with the LG TV remote) to disconnected (when it shows as off in the home app)
> 
> [5/27/2020, 8:25:18 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, state: Offline.
> [5/27/2020, 8:26:37 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, disconnected.

looks like Your TV have state which I can not know, I need the log in Debug mode if this happens.
It is not possible that the tv go offline before disconnected.

**Comment by grzegorz914** [comment] 2020-05-27 05:08
@angyp 
i have prepared test for U check version 105

**Comment by angyp** [comment] 2020-05-27 05:33
Yeah well, that works better as soon as offline is reported the TV shows as off in the Home app. That's about 5 seconds after you hit the button on the LG TV remote.

**Comment by grzegorz914** [comment] 2020-05-27 05:35
OK,
fo 100% fix that please report the Log in debug mode, because I do not know what data is send from Your TV if that happened

**Comment by angyp** [comment] 2020-05-27 05:49
In debug mode, I only get this about 5 seconds after I turn the TV off using the LG TV remote.
 
[5/27/2020, 3:44:13 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, state: Offline.

I think your fix only works when I am running on external ARC speakers if I use the internal speakers it behaves as it did before waits until disconnect shows before showing off in the home app.

**Comment by grzegorz914** [comment] 2020-05-27 05:51
disconnect the external speaker and test it, maybe U have problems with HDMI-CEC test this if nothing external is connected to the tv

**Comment by angyp** [comment] 2020-05-27 06:00
In fact, it has nothing to do with the input or the sound output selected. Your fix only works once per restart of home bridge. The first turn off via LG TV remote works but subsequent ones have to wait the 1 min 20 for the disconnect to come up in the log.

**Comment by angyp** [comment] 2020-05-27 06:07
Actually I think I spoke too soon seems to be working reliably now for some reason

**Comment by angyp** [comment] 2020-05-27 06:21
Worked it out. 

When the offline comes in the home app changes the TV status to off. But if you query it again before the disconnect comes along it shows the TV as ON in the home app.

**Comment by grzegorz914** [comment] 2020-05-27 14:37
> Worked it out.
> 
> When the offline comes in the home app changes the TV status to off. But if you query it again before the disconnect comes along it shows the TV as ON in the home app.

Please post the log in Debug Mode, in other cases I don't know what the TV report

**Comment by angyp** [comment] 2020-05-29 00:29
Hi,
looks like it's resolved in 0.11.114 so thanks.

**Comment by ramirocaballero** [comment] 2020-05-29 21:58
Hi! It work's now! thanks

**Comment by justinrhodes** [comment] 2020-05-29 22:00
Yes, working for me as well now.

What changed?

**Closed** 2020-05-30 03:37 UTC

**Comment by EvgAlex** [comment] 2022-03-01 21:14
Hi, Friend. When i turn off TV in Home app TV is turn off but in HomeKit app TV is TURN on.  if tap again in Home App tv is Turn off. Help Please. Debug
[3/2/2022, 12:13:38 AM] [LgWebOsTv] Device: 192.168.1.85 Телевизор Спальня, Connected.
[3/2/2022, 12:13:38 AM] [LgWebOsTv] -------- Телевизор Спальня --------
[3/2/2022, 12:13:38 AM] [LgWebOsTv] Manufacturer: LG Electronics
[3/2/2022, 12:13:38 AM] [LgWebOsTv] Model: OLED55GXRLA
[3/2/2022, 12:13:38 AM] [LgWebOsTv] System: webOSTV 5.0
[3/2/2022, 12:13:38 AM] [LgWebOsTv] Serialnr: 64:95:6c:fe:08:ff
[3/2/2022, 12:13:38 AM] [LgWebOsTv] Firmware: 03.21.18
[3/2/2022, 12:13:38 AM] [LgWebOsTv] ----------------------------------
[3/2/2022, 12:13:39 AM] [LgWebOsTv] Device: 192.168.1.85 Телевизор Спальня, Specialized socket connected.
[3/2/2022, 12:13:52 AM] [LgWebOsTv] Device: 192.168.1.85 Телевизор Спальня, set Power state successful: OFF
[3/2/2022, 12:14:02 AM] [LgWebOsTv] Device: 192.168.1.85 Телевизор Спальня, Specialized socket disconnected.
[3/2/2022, 12:14:06 AM] [LgWebOsTv] Device: 192.168.1.85 Телевизор Спальня, Disconnected.

**Comment by EvgAlex** [comment] 2022-03-01 21:15
If i restart HomeKit app. All good, tv is TURN off
